[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), interest-cohort=()"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://unpkg.com https://cdnjs.cloudflare.com https://gc.zgo.at; style-src 'self' 'unsafe-inline'; worker-src blob: https://unpkg.com https://cdnjs.cloudflare.com; img-src 'self' data: blob:; connect-src 'self' blob: https://unpkg.com https://cdnjs.cloudflare.com https://madebybala.goatcounter.com; font-src 'self' data:;"

[[headers]]
  for = "*.pdf"
  [headers.values]
    Content-Type = "application/pdf"
    Content-Disposition = "attachment"
